name: Build j-antplus with Bazel
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - master
      - bazel
  pull_request:
    types: [ assigned, opened, synchronize, reopened  ] # Defaults

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # No need to test on multiple operating systems
        os: [ubuntu-latest]
        bazelisk: [1.11.0]
        bazel: [4.2.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Run unit tests
        run: bazel test --test_output=all --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //:junit_tests
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest, ubuntu-latest]
        bazelisk: [1.11.0]
        bazel: [4.2.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build Library
        run: bazel build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //:j_antplus
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

      # See https://github.com/actions/upload-artifact/issues/92#issuecomment-691767977
      - name: Copy library JAR out of symlinked directory
        run: cp bazel-bin/j_antplus-project.jar j_antplus.jar
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

      - name: Save executable artifacts
        uses: actions/upload-artifact@v2
        # Windows and Linux JAR should be the same. Don't need both
        if: runner.os == 'Linux'
        with:
          name: j_antplus.jar
          path: j_antplus.jar

  javadoc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        bazelisk: [1.11.0]
        bazel: [4.2.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build Library
        run: bazel build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //:j_antplus-docs
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

      # See https://github.com/actions/upload-artifact/issues/92#issuecomment-691767977
      - name: Copy library JAR out of symlinked directory
        run: cp bazel-bin/j_antplus-docs.jar .
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

      - name: Save executable artifacts
        uses: actions/upload-artifact@v2
        # Windows and Linux JAR should be the same. Don't need both
        if: runner.os == 'Linux'
        with:
          name: j_antplus-docs.jar
          path: j_antplus-docs.jar
